### ISSUE TITLE
mac + brew + python + jupyter + poetry = insanity?

### ISSUE THREAD

**Issue by setegonz** [matangover/poetry-kernel#1]
Hi. Thank you for making this tool available.  

This is not a problem with your code but I think it's a productive discussion.

I need a working environment for data science. The first thing I did was to install pyenv via brew to have different python installations without interfering with the system versions. Now I don't know whether to install jupyter via brew as well. If I install jupyter via brew; where do I install the packages I need? I have this doubt because I don't know if I want to install the packages I need to work with data science in the global version of python or in a local directory.

I found your Kernel trying to solve this issue that has been bothering me for some weeks now. And I would like to know if you can enlighten me about the options I have besides using your Kernel.

**Comment by matangover** [comment]
Hi! I suggest to install jupyter using pipx :)

https://github.com/pipxproject/pipx

**Comment by setegonz** [comment]
@matangover If I install jupyter with "pipx", how do I install the packages I need to work on jupyter (numpy pandas matplotlib seaborn scikit-learn)?. Do I have to activate a virtual environment to install them from the terminal, or should I install from the same jupyter notebook?

**Comment by matangover** [comment]
Jupyter itself is a server that manages several notebook execution kernels. Your actual code (in the notebooks, where you need numpy etc) is run by a Jupyter kernel. The place you install Jupyter itself doesn't matter too much - that's why I suggested pipx. 

For installing the kernels, you have several options I can think of:
1. Install all data science packages in the global Python installation, and use the global Python installation for your kernel. You said you don't want that as it clutters the global installation, and I agree.
2. Use a 'data science' virtual environment and in it install all data science packages. Also install in it the 'ipykernel' package and install this kernel into your Jupyter installation. Instructions for this are [here](https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-different-environments).
3. Use a separate virtual environment for EACH notebook project, so that if one of them e.g. needs numpy version 1 and the other needs numpy version 2, you can still manage this independently for every notebook (or set of notebooks). You can do this manually using the same instructions as in #2, but this is cumbersome. Using my poetry-kernel makes it easier to create a separate virtual environment for each notebook project.

**Comment by setegonz** [comment]
Your answer is very enlightening. As soon as I get back to work on Monday I'm going to try to use your Kernel.

**Comment by matangover** [comment]
Great :) let me know how it goes.

**Comment by setegonz** [comment]
I'm trying to use the Kernel but I can't get it to work. 
The kernel was installed in:
/Users/setegonz/poetry-kernel

Then I created a folder to start working with a notebook:
/Users/setegonz/MEGAsync/notebook project

Then I tried:
`Stevens-MacBook-Pro:~ setegonz$ python poetry-kernel/new-notebook-project.py /Users/setegonz/MEGAsync/notebook project`

This is what I'm getting:
`Usage: poetry-kernel/new-notebook-project.py <project-directory>`

So i tried:
`Stevens-MacBook-Pro:~ setegonz$ poetry-kernel/new-notebook-project.py /Users/setegonz/MEGAsync/notebook project`

Obtaining the following output: 
from: can't read /var/mail/__future__
poetry-kernel/new-notebook-project.py: line 2: import: command not found
poetry-kernel/new-notebook-project.py: line 3: import: command not found
poetry-kernel/new-notebook-project.py: line 4: import: command not found
from: can't read /var/mail/subprocess
poetry-kernel/new-notebook-project.py: line 7: syntax error near unexpected token `sys.argv'
poetry-kernel/new-notebook-project.py: line 7: `if len(sys.argv) != 2 or sys.argv[1] in ('--help', '-h'):' 





What I'm doing wrong?

**Comment by matangover** [comment]
This is because you have a space in your folder name. Use quotes like so:

```
python poetry-kernel/new-notebook-project.py "/Users/setegonz/MEGAsync/notebook project"
```

**Comment by setegonz** [comment]
Thank you for your time @matangover . From now on I'll see how I make it part of my daily workflow.
